version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 81:81
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - pdfcache:/pdfcache
      - cache:/cache
    networks:
      - websocket_net
      - nginx_dmoj
    depends_on:
      - dmoj

  base:
    image: dmoj-base
    build:
      context: .
      dockerfile: ./base/Dockerfile
    environment: &base_env
      MYSQL_DATABASE: 'dmojdb'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'DATABASE DMOJ PASSWORD'
      MYSQL_ROOT_PASSWORD: 'DATABASE ROOT PASSWORD'
      SECRET_KEY: 'DJANGO SECRET KEY'
      HOST: 'WEBSITE HOSTNAME'
      DEBUG: 0

  dmoj:
    container_name: dmoj
    image: dmoj:dmoj
    build: ./dmoj
    restart: always
    environment: *base_env
    volumes:
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - phantombin:/phantomjs
      - pdfcache:/pdfcache
      - cache:/cache
    networks:
      - nginx_dmoj
      - bridge_net
      - dmoj_dmojdb
      - dmoj_redis
      - dmoj_mathoid
      - websocket_net
    depends_on:
      - dmojdb
      - websocket
      - phantomjs
      - celery
      - mathoid

  dmojdb:
    container_name: dmojdb
    image: mariadb
    restart: always
    environment: *base_env
    volumes:
      - dmojdb_volume:/var/lib/mysql
    networks:
      - dmoj_dmojdb
      - celery_dmojdb
      - bridge_net

  bridge:
    container_name: bridge
    image: bridge:bridge
    build: ./bridge
    restart: always
    environment: *base_env
    ports:
      - 9999:9999
    volumes:
      - ./repo:/online-judge
    networks:
      - bridge_net
      - websocket_net
    depends_on:
      - websocket
      - dmojdb
      - dmoj

  websocket:
    container_name: websocket
    image: websocket:websocket
    build: ./websocket
    restart: always
    volumes:
      - ./repo:/online-judge
    networks:
      - websocket_net

  phantomjs:
    container_name: phantomjs
    image: phantomjs:phantomjs
    build: ./phantomjs
    volumes:
      - phantombin:/phantomjs/bin

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - celery_redis
      - dmoj_redis

  celery:
    container_name: celery
    image: celery:celery
    build: ./celery
    restart: always
    environment: *base_env
    volumes:
      - ./repo:/online-judge
    networks:
      - celery_redis
      - celery_dmojdb
    depends_on:
      - dmojdb
      - redis

  mathoid:
    container_name: mathoid
    image: mathoid:mathoid
    build: ./mathoid
    restart: always
    networks:
      - dmoj_mathoid

networks:
  nginx_dmoj:
    driver: bridge
  websocket_net:
    driver: bridge
  bridge_net:
    driver: bridge
  dmoj_dmojdb:
    driver: bridge
  dmoj_redis:
    driver: bridge
  dmoj_mathoid:
    driver: bridge
  celery_redis:
    driver: bridge
  celery_dmojdb:
    driver: bridge


volumes:
  uwsgi_volume:
  dmojdb_volume:
  cache:
  phantombin:
  pdfcache:
