version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 81:81
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - pdfcache:/pdfcache
    depends_on:
      - dmoj
    networks:
      - websocket_net
      - nginx_dmoj
    container_name: nginx

  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    environment: &base_env
      MYSQL_DATABASE: 'dmojdb'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'DATABASE DMOJ PASSWORD'
      MYSQL_ROOT_PASSWORD: 'DATABASE ROOT PASSWORD'
      SECRET_KEY: 'DJANGO SECRET KEY'
      HOST: 'WEBSITE HOSTNAME'
      DEBUG: 0
    image: dmoj-base

  dmoj:
    build: ./dmoj
    image: dmoj:dmoj
    restart: always
    environment: *base_env
    volumes:
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - phantombin:/phantomjs
      - pdfcache:/pdfcache
    networks:
      - nginx_dmoj
      - bridge_net
      - dmoj_dmojdb
      - dmoj_redis
      - websocket_net
    depends_on:
      - dmojdb
      - websocket
      - phantomjs
      - celery
    container_name: dmoj

  dmojdb:
    image: mariadb
    restart: always
    environment: *base_env
    networks:
      - dmoj_dmojdb
      - celery_dmojdb
      - bridge_net
    volumes:
      - dmojdb_volume:/var/lib/mysql
    container_name: dmojdb

  bridge:
    build: ./bridge
    image: bridge:bridge
    restart: always
    ports:
      - 9999:9999
    volumes:
      - ./repo:/online-judge
    environment: *base_env
    networks:
      - bridge_net
      - websocket_net
    depends_on:
      - websocket
      - dmojdb
      - dmoj
    container_name: bridge

  websocket:
    build: ./websocket
    image: websocket:websocket
    restart: always
    volumes:
      - ./repo:/online-judge
    networks:
      - websocket_net
    container_name: websocket

  phantomjs:
    build: ./phantomjs
    image: phantomjs:phantomjs
    volumes:
      - phantombin:/phantomjs/bin
    container_name: phantomjs

  redis:
    image: redis:alpine
    restart: always
    networks:
      - celery_redis
      - dmoj_redis
    container_name: redis

  celery:
    build: ./celery
    image: celery:celery
    restart: always
    environment: *base_env
    volumes:
      - ./repo:/online-judge
    networks:
      - celery_redis
      - celery_dmojdb
    depends_on:
      - dmojdb
      - redis
    container_name: celery

networks:
  nginx_dmoj:
    driver: bridge
  websocket_net:
    driver: bridge
  bridge_net:
    driver: bridge
  dmoj_dmojdb:
    driver: bridge
  dmoj_redis:
    driver: bridge
  celery_redis:
    driver: bridge
  celery_dmojdb:
    driver: bridge


volumes:
  uwsgi_volume:
  dmojdb_volume:
  phantombin:
  pdfcache:
