version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 81:81
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - pdfcache:/pdfcache
    depends_on:
      - dmoj
    networks:
      - nginx_network
      - websocket_network
    container_name: nginx

  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: dmoj-base

  dmoj:
    build: ./dmoj
    image: dmoj:dmoj
    restart: always
    environment:
      - SECRET_KEY=YOUR SECRET KEY
      - DB_PASSWORD=YOUR DB PASSWORD
    volumes:
      - uwsgi_volume:/uwsgi
      - ./repo:/online-judge
      - phantombin:/phantomjs
      - pdfcache:/pdfcache
    networks:
      - dmojdb_network
      - nginx_network
      - bridge_network
      - websocket_network
    depends_on:
      - dmojdb
      - bridge
      - websocket
      - phantomjs
    container_name: dmoj

  dmojdb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'dmojdb'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'YOUR DB PASSWORD'
      MYSQL_ROOT_PASSWORD: 'YOUR ROOT PASSWORD'
    networks:
      - dmojdb_network
    volumes:
      - dmojdb_volume:/var/lib/mysql
    container_name: dmojdb

  bridge:
    build: ./bridge
    image: bridge:bridge
    restart: always
    ports:
      - 9999:9999
    environment:
      - SECRET_KEY=YOUR SECRET KEY
      - DB_PASSWORD=YOUR DB PASSWORD
    volumes:
      - ./repo:/online-judge
    networks:
      - dmojdb_network
      - bridge_network
      - websocket_network
    depends_on:
      - websocket
      - dmojdb
    container_name: bridge

  websocket:
    build: ./websocket
    image: websocket:websocket
    restart: always
    volumes:
      - ./repo:/online-judge
    networks:
      - websocket_network
    container_name: websocket

  phantomjs:
    build: ./phantomjs
    image: phantomjs:phantomjs
    volumes:
      - phantombin:/phantomjs/bin
    container_name: phantomjs

networks:
  nginx_network:
    driver: bridge
  dmojdb_network:
    driver: bridge
  bridge_network:
    driver: bridge
  websocket_network:
    driver: bridge

volumes:
  uwsgi_volume:
  dmojdb_volume:
  phantombin:
  pdfcache:
